### ISSUE TITLE
Please add BumWings keyboard to the database

### ISSUE THREAD

**Issue by tubbytwins** [YAL-Tools/ergo-keyboards#1]
Generated JSON is here:

{
	"name": "BumWings",
	"img": "https://github.com/tubbytwins/bumwings-kbd/blob/main/doc/bumwings_v001R64_rp2040zero_build_daily.jpg",
	"shape": "Unibody",
	"stagger": "Column",
	"connection": [
		"Wired",
		"Bluetooth"
	],
	"keys": {
		"min": 54,
		"max": 64
	},
	"rows": {
		"min": 3,
		"max": 4
	},
	"cols": 6,
	"rcols": 6,
	"thumbKeys": {
		"min": 2,
		"max": 6
	},
	"innerKeys": {
		"min": 2,
		"max": 4
	},
	"cornerKeys": 2,
	"navCluster": "Full",
	"pinkyStagger": 0.7,
	"splay": "Yes",
	"hotswap": "No",
	"switchProfile": "Choc",
	"keySpacing": "Choc",
	"firmware": [
		"QMK",
		"ZMK"
	],
	"assembly": [
		"PCB",
		"ThroughHole"
	],
	"wristPads": "None",
	"caseType": "None",
	"web": "https://github.com/tubbytwins/bumwings-kbd",
	"source": "https://github.com/tubbytwins/bumwings-kbd"
}

Thanks!

**Comment by YellowAfterlife** [comment]
Thank you! (and that's a cool keyboard)
