### ISSUE TITLE
Updated Lotus58

### ISSUE THREAD

**Issue by TweetyDaBird** [YAL-Tools/ergo-keyboards#2]
{
	"name": "Lotus 58",
	"img": "lotus58.webp",
	"shape": "Split",
	"stagger": "Column",
	"connection": "Wired",
	"keys": 58,
	"rows": 4,
	"cols": 6,
	"rcols": 6,
	"thumbKeys": 4,
	"innerKeys": 1,
	"pinkyStagger": 0,
	"hotswap": "Yes",
	"switchProfile": "MX",
	"keySpacing": "MX",
	"encoders": {
		"min": 0,
		"max": 2
	},
	"encoderType": "Knob",
	"displays": {
		"min": 0,
		"max": 2
	},
	"firmware": "QMK",
	"software": "Vial",
	"assembly": [
		"PCB",
		"ThroughHole"
	],
	"wristPads": "None",
	"tilt": {
		"min": 0,
		"max": 20
	},
	"tenting": {
		"min": 0,
		"max": 20
	},
	"caseType": [
		"Included",
		"ThirdParty"
	],
	"source": "https://github.com/TweetyDaBird/Lotus-Keyboard",
	"kit": "https://lectronz.com/stores/tweetys-wild-thinking",
	"prebuilt": "https://lectronz.com/stores/tweetys-wild-thinking"
}

**Comment by YellowAfterlife** [comment]
Thank you!
