### ISSUE TITLE
Adding Microcontroller layout and Number

### ISSUE THREAD

**Issue by DavidMirror** [YAL-Tools/ergo-keyboards#8]
**Is your feature request related to a problem? Please describe.**
Currently there is no good way to see what each keyboard uses for their microcontroller units (MCUs). This can make a difference, as, different daughter boards can cost vastly different prices or have different capacities. 

Furthermore, projects like ZMK currently don't support wired splits, so seeing the amount of MCUs each board uses could be beneficial if one is considering ZMK for a wired split keyboard (I believe inter-MCU communication is the issue with the split code, but I am not an expert).

**Describe the solution you'd like**
I want to add the number MCUs and MCU interface for each board.

**Describe alternatives you've considered**
The number of MCUs could be a less important factor, and there is less variation (rarely does a unibody board have 2 MCUs and a split board have one), so I could drop that

**Additional context**
I have currently done most boards that I could find information on so far. 

This is the current overall stats that I have for the different boards. The less used ones could be potentially further reduced. 
Elite-C is any Pro Micro with the extra 5 pins at the end. Many boards use boards with Elite-C layout, but most don't actually require the extra pins. I've only included those that require it. I've tried to do the same with the Nice!Nano, which is why there are so few, but I may have to go back and review those. The Wireless/Wired data currently in the list may be enough to determine which currently.

![image](https://github.com/YAL-Tools/ergo-keyboards/assets/6633322/d9889a15-ff93-4723-8901-98b9b78d9465)

The category Onboard usually refers to surface mount components or premade boards, but may refer to daughter boards that are also surface mount.

Here is my currently very messy google sheets file that I've been recording this data in. I am still unsure how to convert to JSON and integrate it to individual boards.
https://docs.google.com/spreadsheets/d/1n3GiSTfl841fM2TmFexftcDNppRMkwo9DEgcTyAcpHA/edit?usp=sharing

**Comment by YellowAfterlife** [comment]
Closed through #10
